### ISSUE TITLE
YAML Configuration | AMSUA

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#59] opened 2022-05-12 14:17 UTC
## Agreement with GSI using GeoVaLs in UFO (Hofx no bias correction)

- [x] AQUA
- [x] METOP-A
- [x] METOP-B
- [x] METOP-C
- [x] NOAA-15
- [x] NOAA-18
- [x] NOAA-19

## Agreement with GSI using GeoVaLs in UFO (Bias correction)

- [x] AQUA
- [x] METOP-A
- [x] METOP-B
- [x] METOP-C
- [x] NOAA-15
- [x] NOAA-18
- [x] NOAA-19

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] AQUA
- [x] METOP-A
- [x] METOP-B
- [x] METOP-C
- [x] NOAA-15
- [x] NOAA-18
- [x] NOAA-19

## Agreement with GSI using GeoVaLs in UFO (Hofx with bias correction)

- [x] AQUA
- [x] METOP-A
- [x] METOP-B
- [x] METOP-C
- [x] NOAA-15
- [x] NOAA-18
- [x] NOAA-19

## Agreement with GSI using Swell

- [ ] AQUA
- [ ] METOP-A
- [ ] METOP-B
- [ ] METOP-C
- [ ] NOAA-15
- [ ] NOAA-18
- [ ] NOAA-19

## Current issues:

- Need new GeoVaLs from GSI

**Comment by gmao-yzhu** [comment] 2022-05-12 19:24
AMSU-A NOAA19 has passed UFO tests, code changes and two new yaml files were merged into UFO develop.

**Comment by gmao-yzhu** [comment] 2022-05-18 20:58
When testing NOAA18, I found that UFO results didn't match with GSI. Jianjun made plots and further narrowed the issue down to the locations over ice, i.e., when ice-fraction=1 and sst=260.

I diff-ed CRTM code and fixed files and confirmed we are using the same version in GSI with UFO. 
When I read the CRTM codes, I noticed that over ice, sst will be re-set to 260 if it is >= 280. 

So this issue may have something to do with how surface type is decided and sst values in geoval file. In GSI, it is considered as ice when ice-fraction>0.99.  Jianjun is re-generating testing files to see if new files will make any difference.

**Comment by gmao-yzhu** [comment] 2022-05-19 04:29
@gmao-jjin3 I added some printout from UFO calculation.

Here are the locations where sst=260.0 with inconsistent Tb with GSI:
```
         profile.   ice-frac.     sst.           Tb
19: fICE2:  2490       1.000     260.000     263.785
19: fICE2:  2760       1.000     260.000     262.909
19: fICE2:  2785       1.000     260.000     264.405
19: fICE2:  2896       1.000     260.000     262.299
19: fICE2:  4587       1.000     260.000     266.696
19: fICE2:  4609       1.000     260.000     267.810
19: fICE2:  5371       0.957     260.000     261.166
19: fICE2:  5891       1.000     260.000     258.306
19: fICE2:  6125       1.000     260.000     262.895
```

If I printed out the results around profile 2490, you'll see that all nearby profiles' sst=280 but they are over ocean, so it is likely the original sst of profile 2490 is also 280, but it re-set to 260 in crtm because it is over ice (ice-frac=1.0):
```
19: fICE2:  2485       0.000     280.000     196.547
19: fICE2:  2486       0.000     280.000     196.292
19: fICE2:  2487       0.000     280.000     192.273
19: fICE2:  2488       0.000     280.000     183.416
19: fICE2:  2489       0.000     280.000     286.642
19: fICE2:  2490       1.000     260.000     263.785
19: fICE2:  2491       0.000     280.000     283.886
19: fICE2:  2492       0.000     280.000     277.628
19: fICE2:  2493       0.000     280.000     284.318
19: fICE2:  2494       0.000     280.000     189.693
19: fICE2:  2495       0.000     280.000     194.191
```

Similarly, this is what happened around profile 2760:
```
19: fICE2:  2756       0.000     280.000     195.351
19: fICE2:  2757       0.000     280.000     286.910
19: fICE2:  2758       0.000     280.000     284.945
19: fICE2:  2759       0.000     280.000     284.719
19: fICE2:  2760       1.000     260.000     262.909
19: fICE2:  2761       0.000     280.000     268.708
19: fICE2:  2762       0.000     280.000     196.285
19: fICE2:  2763       0.000     280.000     199.958
19: fICE2:  2764       0.000     280.000     288.736
19: fICE2:  2765       0.000     280.000     284.067
```

So in the GSI diag file, these sst at ice locations have already been re-set to 260 and written out in geoval file. You probably need to write out the sst values before it is re-set to 260 during the crtm calculation.

**Comment by gmao-jjin3** [comment] 2022-05-19 05:17
@gmao-yzhu  I think you nailed it!

**Comment by gmao-jjin3** [comment] 2022-05-20 19:32
@gmao-yzhu   The x0044 was re-run after some modification in GSI which now stores the CRTM input values of "ice_temperature".  I had a quick UFO test using those testing files made from my new GEOS outputs.  The GSI Hofx can be fully reproduced in UFO now. See a comparison  between those Hofx before bias correction in /discover/nobackup/jjin3/jedi/swell_output/amsua/ufo_output_woBC/newIODA/.

**Comment by gmao-jjin3** [comment] 2022-05-20 19:40
@gmao-yzhu. You should set your CRTM coefficient files' path to the directory which has locally modified values when using these new testing files:
CoefficientPath: /gpfsm/dnb52/projects/p10/gmao_ops/fvInput_4dvar/gsi/etc/fix_ncep20210525/REL-2.2.3-r60152_local-rev_5/CRTM_Coeffs/Little_Endian/

**Comment by gmao-yzhu** [comment] 2022-05-24 13:00
@gmao-jjin3 Thank you for generating the testing files and for testing them. Could you pass me the location of the files?

**Comment by gmao-yzhu** [comment] 2022-05-24 13:09
@gmao-jjin3 I'm also wondering if there is any inconsistency in the calculation of ice locations of such scenario in the CRTM.  In an area with SST=280, the value of SST is re-set to 260 at ice locations in the surface part calculation but it seems 280 is still used somewhere at these ice locations.  I will check with CRTM team.

**Comment by gmao-jjin3** [comment] 2022-05-24 17:43
@gmao-yzhu   You can use this command to find the data: e.g., amsua_n19:
**find $NOBACKUP/jedi/For_others/x0044j -iname "*amsua_n19*"**
As to your question, the surface temperature is only changed when surface is "ice" for AMSUA. It is not changed when surface is "snow". Not sure about the impact.

**Comment by gmao-yzhu** [comment] 2022-05-25 21:49
Using the new testing files Jianjun produced -- 

The tests of UFO HofX (w/o BC) of all AMSU-A satellites failed. However ...  
1) this is associated with a new issue, which didn't exist before. In the new testing files, the bad channels or passive channels of GsiHofX are stored with values of zeros, which caused the UFO HofX tests failures.
2) If we set the testing range of Obsvalue to be [-999, 999], which is a very broad reasonable range, or skip the channels with GsiHofX being zeros, we can see that the differences between GSI OmF and UFO OmF are very small, ~1.0e-5. 
3) The scatter plots of GSI OmF and UFO OmF are very nice diagonal straight lines. 
4) the previous failures over ice locations are all gone. 

I tested all AMSU-As with the above steps. I can say with confidence that UFO HofX (w/o BC) step is considered passed. 
The testing files from GSI may need a little minor changes.

**Comment by gmao-yzhu** [comment] 2022-05-25 23:16
The tests of UFO HofX with Bias correction basically have the same situation as the above mentioned UFO HofX w/o BC. Here I post several figures from NOAA18 HofX with bias correction. 
![amsua_n18 UFO_Obs_Number O-F_BC ch04 ps](https://user-images.githubusercontent.com/73974278/170384543-8d5dd029-6241-4e82-8671-723d9f0e254f.png)
![amsua_n18 UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC ch01 ps](https://user-images.githubusercontent.com/73974278/170384560-4b950e07-0b1c-47b2-97b7-8549a5e21c7a.png)
![amsua_n18 UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC ch04 ps](https://user-images.githubusercontent.com/73974278/170384571-2dae4417-0409-41e9-b87b-bb753c3f755b.png)

**Comment by gmao-yzhu** [comment] 2022-05-26 03:04
AMSU_A NOAA18 quality control and observation error test:

fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch01.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -1.04904e-05  1.09673e-05
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch02.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -2.00272e-05  2.14577e-05
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch03.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -1.28746e-05  1.38283e-05
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch04.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -1.96695e-06  2.14577e-06
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch05.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -5.96046e-08  4.76837e-07
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch06.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':   -0.00257641  8.94070e-08
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch07.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -6.28233e-05  2.98023e-08
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch08.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -2.08616e-07  2.98023e-08
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch09.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -2.98023e-08      0.00000
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch10.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -2.98023e-08  2.98023e-08
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch11.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -2.98023e-08  5.96046e-08
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch12.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -5.96046e-08  5.96046e-08
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch13.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -5.96046e-08  1.19209e-07
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch14.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -4.76837e-07  9.53674e-07
fig_name=amsua_n18.UFO_EffectiveError.GsiFinalObsError_QC.ch15.ps
--------- Differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -2.86102e-05  3.14713e-05

Three figures are attached: ch4 histogram after BC and QC; final observation error comparisons for channels 4 & 7
![amsua_n18 UFO_Obs_Number O-F_BC_QC ch04 ps](https://user-images.githubusercontent.com/73974278/170407253-3c2a561a-99e6-42c1-8742-cf53b166e4c2.png)
![amsua_n18 UFO_EffectiveError GsiFinalObsError_QC ch04 ps](https://user-images.githubusercontent.com/73974278/170407295-fa9bd6b6-6482-4e0e-9fcc-94d76fcce550.png)

![amsua_n18 UFO_EffectiveError GsiFinalObsError_QC ch07 ps](https://user-images.githubusercontent.com/73974278/170407647-3549fc57-3214-4032-80ec-68b6cc301c89.png)

**Comment by gmao-jjin3** [comment] 2022-05-26 05:43
@gmao-yzhu  I generated those testing files again. Basically, GSI Hofx values are set to NaN when ObsValues are huge values in the IODA converter.  My UFO tests using new AMSUA data now pass without an error.

**Comment by gmao-yzhu** [comment] 2022-05-26 13:27
@gmao-jjin3 Thanks very much for re-generarting the new testing files. Yes, they are working now. I just tested UFO HofX with bias correction for Metop-C, the ctest passed, with the following results:

Test     : Vector difference between reference and computed: amsua_metop-c nobs= 135208 Min=-8.3672971499026971e-05, Max=8.0261969515049714e-05, RMS=9.5035773574081308e-06

**Comment by gmao-yzhu** [comment] 2022-05-27 20:31
AMSU-A_Metop-C: 2 points out 5179 have smaller final observation errors than GSI. 
AMSUA-n15: 3 points out of 3800 of ch4 have smaller final observation errors than GSI. 
![amsua_metop-c UFO_Obs_Number O-F_BC_QC ch04 ps](https://user-images.githubusercontent.com/73974278/170785230-fa3f4601-0fcb-41b3-98bb-f35c4b98e514.png)
![amsua_metop-c UFO_EffectiveError GsiFinalObsError_QC ch04 ps](https://user-images.githubusercontent.com/73974278/170785248-354acff6-741f-4c93-8ebe-a34d6a68cd84.png)

**Comment by gmao-yzhu** [comment] 2022-05-27 20:55
AMSU-A_Metop-a also has 2 points out 3608 have smaller final observation errors than GSI.

**Comment by gmao-yzhu** [comment] 2022-05-27 21:58
In summary, UFO testings: 

1. Code changes were merged into JEDI UFO develop (pull requests #1899, 1938, 1981). 
2. Tb CRTM simulations, bias corrections, data passing quality control, OmF histogram match well with GSI results.
3. Final observation errors from UFO generally match well with GSI, but noticeable differences are observed as the following: AMSU-A_Metop-a, Metop-c each has 2 points and n15 has 3 points that have smaller final observation errors than GSI. 

Please note -- in all the UFO testings, 1) those locations where obsvalue has very large values are not considered. 
2) According to the testing files from GSI, AMSU-A_Aqua ch14 is bias corrected while other AMSU-A ch14 are not bias corrected, so be careful with the handlings of ch14 in yaml files.

**Comment by danholdaway** [comment] 2022-06-16 01:30
@gmao-yzhu @rgelaro I made the same plots we looked at yesterday but from the data Yanqui's UFO with GSI GeoVaLs run put out. Can confirm that we do not see the same problems. I think the first thing we need to check is that we are using the same bias correction files. I strongly suspect not and that swell is picking up the incorrect files. Yanqui/@gmao-jjin3  would you be able to point me to the satbias files that are being used in the UFO testing? More importantly can you point me to the files in x0044 where they were computed from? I want to make sure the workflow picks up the correct files. 

Although I don't see the same problems as with Swell I did see something we might want to investigate. E.g. see the attached plot for channel 15. The plot shows UFO h(x) minus GSI h(x). There are a small number of points that are different. For window channels they are quite different. Is this expected? The same points show up for all channels to some extent. I'm not sure I understand how the tests would pass unless it's just that there are enough points doing well to hide these points in a global RMS (or whatever UFO computes to check things are OK).  The points I see are over Australia and NZ, South America and Asia.

![gsi_omb_minus_jedi_omb_amsua_n19_brightness_temperature_15](https://user-images.githubusercontent.com/27729500/173972092-990dae9c-9b84-4bbe-9bd5-4ea75ca2b019.png)

**Comment by gmao-jjin3** [comment] 2022-06-16 02:45
@danholdaway  I believe Yanqiu uses data in /discover/nobackup/jjin3/jedi/For_others/x0044j/ . You can search bias correction, geoval, and observational files by a command like :
find /discover/nobackup/jjin3/jedi/For_others/x0044j -iname "\*amsua_n19\*"

These data are made from  /archive/u/jjin3/x0044.jj_20220520/
I did produce some new X0044 results in order to solve Wei's issue. Now running the x0044 again in order to update satellite wind diagnostic files. I'll distribute new testing files later.

**Comment by rgelaro** [comment] 2022-06-16 12:54
Thanks, Dan.

Wei reported again yesterday that, also for the IR, he finds one or a few obs that don't match between UFO and GSI.  The points in your plot are always so close to the coast, I wonder if there's a mask, land-type, or interpolation between land and sea that's just a bit off between the two systems.

Ron
________________________________
From: Dan Holdaway ***@***.***>
Sent: Wednesday, June 15, 2022 9:30 PM
To: GEOS-ESM/swell ***@***.***>
Cc: Gelaro, Ronald (GSFC-6101) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/swell] YAML Configuration | AMSUA (Issue #59)


@gmao-yzhu<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgmao-yzhu&data=05%7C01%7Cronald.gelaro-1%40nasa.gov%7C895ff46c27264fdf562408da4f37d713%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637909398501966688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jhWLPuycwhLfqISt%2F1HdvuyuW7j%2F5sybSrE38FkbmXU%3D&reserved=0> @rgelaro<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frgelaro&data=05%7C01%7Cronald.gelaro-1%40nasa.gov%7C895ff46c27264fdf562408da4f37d713%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637909398501966688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LUsUlscgmSslGISiFF5bP2MXkYY8Eyktr79fFBlFC0w%3D&reserved=0> I made the same plots we looked at yesterday but from the data Yanqui's UFO with GSI GeoVaLs run put out. Can confirm that we do not see the same problems. I think the first thing we need to check is that we are using the same bias correction files. I strongly suspect not and that swell is picking up the incorrect files. ***@***.***<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgmao-jjin3&data=05%7C01%7Cronald.gelaro-1%40nasa.gov%7C895ff46c27264fdf562408da4f37d713%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637909398501966688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EdlFz%2FQe%2FEGqa4QVTkuZqK4VuefjT2Xee5aLHqocya0%3D&reserved=0> would you be able to point me to the satbias files that are being used in the UFO testing? More importantly can you point me to the files in x0044 where they were computed from? I want to make sure the workflow picks up the correct files.

Although I don't see the same problems as with Swell I did see something we might want to investigate. E.g. see the attached plot for channel 15. The plot shows UFO h(x) minus GSI h(x). There are a small number of points that are different. For window channels they are quite different. Is this expected? The same points show up for all channels to some extent. I'm not sure I understand how the tests would pass unless it's just that there are enough points doing well to hide these points in a global RMS (or whatever UFO computes to check things are OK). The points I see are over Australia and NZ, South America and Asia.

[gsi_omb_minus_jedi_omb_amsua_n19_brightness_temperature_15]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F27729500%2F173972092-990dae9c-9b84-4bbe-9bd5-4ea75ca2b019.png&data=05%7C01%7Cronald.gelaro-1%40nasa.gov%7C895ff46c27264fdf562408da4f37d713%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637909398501966688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IwOg7Cqmx9vc1t%2BnIkM3aodlcbnQ78nCNYYeUhUxS2o%3D&reserved=0>

**Comment by gmao-yzhu** [comment] 2022-06-16 15:03
Dan, 

UFO checked the maximum and minimum as well as RMSE. I recall I didn't see those large values in max, min and RMSE. One possibility is that UFO excluded unreasonable observations in its verification. I know that is also what Jianjun did in his plotting tool.  Could you make a plot of observation value? 

Thanks,
Yanqiu

**Comment by gmao-yzhu** [comment] 2022-06-16 17:39
Dan, 

I re-ran the AMSU-A NOAA18 ufo test, here is the comparison statistics results of OmF after bias correction:

23: Test     : Vector difference between reference and computed: amsua_n18 nobs= 137076 Min=-6.7971999527571825e-05, Max=8.2725437550834613e-05, RMS=9.1908880846134932e-06

Yanqiu

**Comment by danholdaway** [comment] 2022-06-16 19:25
OK. Thanks for checking. That definitely sounds good enough!

**Comment by gmao-yzhu** [comment] 2022-06-16 20:44
Here is comparison results for amsua noaa19 OmF after bias correction:

18: Test     : Vector difference between reference and computed: amsua_n19 nobs= 138938 Min=-4.4930507613116788e-05, Max=4.8407639155811921e-05, RMS=7.5823839249824830e-06

**Comment by danholdaway** [comment] 2022-06-16 20:47
Thanks @gmao-yzhu! Good to know. I wonder what could be causing the difference in the plots. I'll focus on trying to understand the differences with swell for now.

**Closed as completed** 2023-09-22 16:40 UTC
Labels: ufo done
