### ISSUE TITLE
YAML Configuration | GMI

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#66] opened 2022-05-12 16:39 UTC
## Agreement with GSI using GeoVaLs in UFO (Hofx no bias correction)

- [x] GPM

## Agreement with GSI using GeoVaLs in UFO (Bias correction)

- [x] GPM

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] GPM

## Agreement with GSI using GeoVaLs in UFO (Hofx with bias correction)

- [x] GPM

## Agreement with GSI using Swell

- [ ] GPM

## JEDI PRs

- [x] https://github.com/JCSDA-internal/ufo/pull/2179
- [ ] https://github.com/JCSDA-internal/ufo/pull/2230
- [x] #111

## Current issues:

- Cloud index needed in the bias correction. Currently not available in the UFO. 
- YZ: suggestion to add cloud calculations to bias correction part.

**Comment by gmao-jjin3** [comment] 2022-05-25 14:06
There is a pending issue (https://github.com/JCSDA-internal/ufo-data/issues/164) that adding bias correction to hofx values before they are used for cloud retrievals.  As a result, validation of GMI quality control on-hold at the moment.

**Comment by gmao-jjin3** [comment] 2022-07-26 18:50
![gmi_gpm UFO_clw_guess_ret_jedi clw_guess_retrieval ch5 ps](https://user-images.githubusercontent.com/61251050/181087813-980df199-9401-4782-b0a1-0e0c82a27f49.png)
![gmi_gpm UFO_clw_obs_ret_jedi clw_obs ch5 ps](https://user-images.githubusercontent.com/61251050/181087828-2368d2bc-757e-475f-9dc6-e54b9ccd0add.png)

Clouds can be derived correctly in JEDI.  X-axis, clouds from GSI; Y-axis, clouds from JEDI.

**Comment by gmao-jjin3** [comment] 2022-07-26 18:53
![gmi_gpm UFO_EffectiveError GsiFinalObsError_QC ch05 ps](https://user-images.githubusercontent.com/61251050/181088389-f9fefab3-2be2-4e45-bc02-048d99a3308d.png)
![gmi_gpm UFO_EffectiveError GsiFinalObsError_QC ch13 ps](https://user-images.githubusercontent.com/61251050/181088405-38522fd9-008d-44e5-b699-7203731ae017.png)

GIS obervational errors (x-axis) are reproduced in JEDI as well (y-axis).

**Comment by gmao-jjin3** [comment] 2022-08-02 02:22
Departures of GMI data in GEOS are fully reproduced in UFO after its bias correction is finalized in UFO. There is git-hub pull request for the latest update: https://github.com/JCSDA-internal/ufo/pull/2179.  Here are departure difference ranges and observational error difference ranges:
***********  ch01 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -4.57764e-05  4.57764e-05
***********  ch02 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -1.52588e-05  2.28882e-05
***********  ch03 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -1.52588e-05  3.05176e-05
***********  ch04 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -1.52588e-05  3.05176e-05
***********  ch05 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -3.05176e-05  3.05176e-05
***********  ch06 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -3.05176e-05  6.10352e-05
***********  ch07 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -1.52588e-05  1.52588e-05
***********  ch08 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -3.05176e-05  3.05176e-05
***********  ch09 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -3.05176e-05  3.05176e-05
***********  ch10 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -3.05176e-05  3.05176e-05
***********  ch11 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -3.05176e-05  3.05176e-05
***********  ch12 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -3.05176e-05  3.05176e-05
***********  ch13 differences 'UFO_ObsValue-hofx_BC_QC' - 'ObsValue-GsiHofXBc_BC_QC':  -3.05176e-05  3.05176e-05

***********  ch01 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -1.90735e-06  1.90735e-06
***********  ch02 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -3.81470e-06  3.81470e-06
***********  ch03 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -3.81470e-06  3.81470e-06
***********  ch04 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -3.81470e-06  3.81470e-06
***********  ch05 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -3.43323e-05  4.19617e-05
***********  ch06 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -2.86102e-05  2.95639e-05
***********  ch07 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -0.000869751  0.000839233
***********  ch08 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -3.81470e-06  3.81470e-06
***********  ch09 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -3.81470e-06  3.81470e-06
***********  ch10 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -7.24792e-05  9.53674e-05
***********  ch11 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -3.81470e-06  3.81470e-06
***********  ch12 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -4.57764e-05  5.72205e-05
***********  ch13 differences 'UFO_EffectiveError_QC' - 'GsiFinalObsError_QC':  -5.53131e-05  7.24792e-05

**Comment by gmao-jjin3** [comment] 2022-08-02 04:35
![gmi_gpm UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch05 ps](https://user-images.githubusercontent.com/61251050/182292553-2a9893c6-5781-4543-91d6-302836d47f56.png)
![gmi_gpm UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch13 ps](https://user-images.githubusercontent.com/61251050/182292559-bb5cdd09-00a3-4101-976a-d59e191f63ff.png)

**Comment by gmao-jjin3** [comment] 2022-08-23 14:28
![gmi_gpm UFO_Obs_Number O-F_BC_QC ch05 ps](https://user-images.githubusercontent.com/61251050/186184571-d5447bdc-26ce-4e06-ba10-d02d402f6546.png)
![gmi_gpm UFO_Obs_Number O-F_BC_QC ch06 ps](https://user-images.githubusercontent.com/61251050/186431884-23c6a744-e54f-4e3a-bde3-3a54db3fdb91.png)
![gmi_gpm UFO_Obs_Number O-F_BC_QC ch10 ps](https://user-images.githubusercontent.com/61251050/186184674-949dcde9-9ff1-4b8c-abf9-a241e9b2061d.png)
![gmi_gpm UFO_Obs_Number O-F_BC_QC ch11 ps](https://user-images.githubusercontent.com/61251050/186184711-b8579427-e222-4efb-903d-00c2c71560fd.png)
![gmi_gpm UFO_Obs_Number O-F_BC_QC ch12 ps](https://user-images.githubusercontent.com/61251050/186433956-4cbb8d5c-ac2c-4fd3-9eaa-29d7d5b46662.png)
![gmi_gpm UFO_Obs_Number O-F_BC_QC ch13 ps](https://user-images.githubusercontent.com/61251050/186184727-e1e54f5a-50c0-47d9-b662-feb1a01f373c.png)

**Comment by gmao-jjin3** [comment] 2022-08-23 14:41
There are a few more data screened out by UFO filters than by GSI.  That is because a minor 'bug' in GSI. The retrieval error flag is not checked  when clouds are retrieved using simulated Tb and simulated Tb assuming clear-sky conditions. 
```
           if(gmi) then
             call gmi_37pol_diff(tsim_bc(6),tsim_bc(7),tsim_clr_bc(6),tsim_clr_bc(7),clw_guess_retrieval,ierrret)
             call gmi_37pol_diff(tb_obs(6),tb_obs(7),tsim_clr_bc(6),tsim_clr_bc(7),clw_obs,ierrret)
           end if
           ......
           if (ierrret /= 0) then
                varinv(1:nchanl)=zero
                id_qc(1:nchanl) = ifail_cloud_qc
           endif

```
Only the 2nd ierrret is checked in the GSI program setuprad.f90.

**Comment by gmao-jjin3** [comment] 2022-08-23 14:45
Waiting for the merge of the UFO PR: https://github.com/JCSDA-internal/ufo/pull/2230 .

**Comment by danholdaway** [comment] 2022-08-23 15:03
Great stuff @gmao-jjin3! Thanks for working through all the challenges.

**Comment by gmao-jjin3** [comment] 2022-09-07 16:28
Here is the PR to correctly convert GMI bias correction coefficients:
https://github.com/JCSDA-internal/ioda-converters/pull/1042

**Comment by gmao-jjin3** [comment] 2023-05-15 01:39
@gmao-yzhu @danholdaway  The HofX of GMI in x0048 indeed can be reproduce by UFO with CRTM v2.4.0.
![corscat_omb_vs_gsiomb_5](https://github.com/GEOS-ESM/swell/assets/61251050/3e69dd5a-06af-4a55-a66f-fe9e8aa772b5)

**Comment by danholdaway** [comment] 2023-05-15 13:19
Thanks for checking that out @gmao-jjin3

**Comment by gmao-jjin3** [comment] 2023-06-30 20:00
![gsi_omb_jedi_omb_density_gmi_gpm_brightnessTemperature_5](https://github.com/GEOS-ESM/swell/assets/61251050/d1c00656-d1a7-4a5d-bff2-8e332cc0518f)
![gsi_omb_jedi_omb_density_gmi_gpm_brightnessTemperature_6](https://github.com/GEOS-ESM/swell/assets/61251050/cc5aca9b-ba0c-488d-8dde-2436f0d360c8)
![gsi_omb_jedi_omb_density_gmi_gpm_brightnessTemperature_7](https://github.com/GEOS-ESM/swell/assets/61251050/543b0da1-57d0-436b-b581-16e2541bb2d9)
![gsi_omb_jedi_omb_density_gmi_gpm_brightnessTemperature_10](https://github.com/GEOS-ESM/swell/assets/61251050/4cd01151-9c50-4d70-a34a-eb754b676e1a)
![gsi_omb_jedi_omb_density_gmi_gpm_brightnessTemperature_12](https://github.com/GEOS-ESM/swell/assets/61251050/6bb118c0-30be-4459-9353-458c5cc7ad9b)
![gsi_omb_jedi_omb_density_gmi_gpm_brightnessTemperature_13](https://github.com/GEOS-ESM/swell/assets/61251050/c2bb864b-3afd-430c-8ccf-55557c126076)

New validation using results of the x0048 experiment. Get the same conclusion as for x0044 in August 2022. GSI results of O-F and QC can be reproduced by UFO, but there are a few more observations tossed by UFO for channels 10-13.  The reason was posted in https://github.com/GEOS-ESM/swell/issues/66#issuecomment-1224173465. 
A GSI PR https://github.com/GEOS-ESM/GEOSana_GridComp/pull/137 is made for future GEOS update.

**Comment by gmao-jjin3** [comment] 2023-07-01 03:41
![corscat_obserr_vs_gsiobserr_Qc_ch5](https://github.com/GEOS-ESM/swell/assets/61251050/b98a4edc-29bb-47b4-a75e-03b29ec3d818)
![corscat_obserr_vs_gsiobserr_Qc_ch6](https://github.com/GEOS-ESM/swell/assets/61251050/4da0c202-0821-4ed4-98a4-5aaf6a2575d5)
![corscat_obserr_vs_gsiobserr_Qc_ch7](https://github.com/GEOS-ESM/swell/assets/61251050/80e2beb0-4125-4b99-9259-6ece256b2016)
![corscat_obserr_vs_gsiobserr_Qc_ch10](https://github.com/GEOS-ESM/swell/assets/61251050/b4a5f4dc-cf79-484d-920a-22b7cd8263be)
![corscat_obserr_vs_gsiobserr_Qc_ch12](https://github.com/GEOS-ESM/swell/assets/61251050/62268036-6e1b-40f9-8ef3-573dad844b63)
![corscat_obserr_vs_gsiobserr_Qc_ch13](https://github.com/GEOS-ESM/swell/assets/61251050/b811f486-ad9e-4c09-9634-0516263b2514)

Here are comparisons of observational errors in JEDI and GSI.

**Closed as completed** 2023-09-22 16:40 UTC
Labels: ufo done
