### ISSUE TITLE
YAML Configuration | Aircraft

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#60] opened 2022-05-12 16:36 UTC
## Agreement with GSI using GeoVaLs in UFO (Hofx no bias correction)

- [x] Done

## Agreement with GSI using GeoVaLs in UFO (Bias correction)

- [ ] Done

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [ ] Done

## Agreement with GSI using GeoVaLs in UFO (Hofx with bias correction)

- [ ] Done

## Agreement with GSI using Swell

- [ ] Done

## Current issues:

- [x] https://github.com/JCSDA-internal/ufo/pull/2218
- Need updates to GSI in order to write station ID (tail number?) to the ncdiags.
- Would need the ascent rate (vertical velocity) in the IODA files. Written by GSI but not covered by converters.

**Comment by gmao-msienkie** [comment] 2022-06-14 16:48
The original YAML file attempts to assign observation errors for specific KXs via the 'Bounds Check' filter.  These will be replaced with 'Perform Action'.

**Comment by gmao-msienkie** [comment] 2022-06-29 23:07
In order to match our GSI, the ObsErrorFactorConventional filter will need to be modified to work like the errormod_aircraft code with additional checks for horizontal distance between aircraft observations.

**Comment by danholdaway** [comment] 2022-08-10 14:47
In setting up the run for Meta I generated the GSI hofx vs JEDI hofx plots for aircraft to make sure it was working. 

Here is the plot for temperature (not bias corrected)

![gsi_hofx_vs_jedi_hofx_air_temperature](https://user-images.githubusercontent.com/27729500/183932529-aec5eda6-6ea5-40ce-9ca6-ae7b81114636.png)

A perfect match. However here are the plots for wind:

![gsi_hofx_vs_jedi_hofx_eastward_wind](https://user-images.githubusercontent.com/27729500/183932790-1784ee53-a017-4e3e-86a8-b8c01a91a702.png)

![gsi_hofx_vs_jedi_hofx_northward_wind](https://user-images.githubusercontent.com/27729500/183932796-74f2f670-f33b-4575-8332-88796bcfc3ee.png)

These pattens probably look familiar to @asewnath !

**Comment by gmao-msienkie** [comment] 2022-08-10 20:02
The difference in Jedi HofX and GSI HofX could be due to proximity to the surface.  When I plotted observations only above 600 hPa there was good agreement between the two.

**Comment by gmao-msienkie** [comment] 2022-08-10 20:25
![press_dist_0 1diff](https://user-images.githubusercontent.com/53273921/184013175-ae7bd8e2-19fc-4320-8026-368186abbb6c.png)

**Comment by danholdaway** [comment] 2022-08-10 20:59
Thanks for uploading the plots @gmao-msienkie

**Comment by gmao-msienkie** [comment] 2022-08-11 23:21
There is a dataset "wind_reduction_factor_at_10m" in the wind geovals file that contains the 'factw' factor used to reduce the wind speed near the surface.  Here is a plot comparing the uHofX from the GSI with uHofX JEDI and with uHofX*factw - this wind reduction factor is needed to have the UFO output agree with the GSI.
![uHofX_with_factw](https://user-images.githubusercontent.com/53273921/184258260-d8ff7fae-1326-4353-8df4-db0af02a7c75.png)

**Comment by danholdaway** [comment] 2022-08-12 12:35
Voila! Thanks for tracking this down @gmao-msienkie. Does this require some source code changes in JEDI?

**Comment by danholdaway** [comment] 2022-08-12 12:38
Is `wind_reduction_factor_at_10m` something that would come in the PREPBUFR? If not I wonder if we should be recomputing `wind_reduction_factor_at_10m` in JEDI. So we don't end up having to revisit this when we start going from BUFR instead of NCDiags for the JEDI obs.

**Comment by gmao-msienkie** [comment] 2022-08-12 13:42
> Voila! Thanks for tracking this down @gmao-msienkie. Does this require some source code changes in JEDI?

I think it will need some code changes.  I didn't see anything resembling this operation in the documentation.  It would also apply to the satellite winds so Akira could also take a look to see if I missed something.

**Comment by rgelaro** [comment] 2022-08-12 13:48
This is great to see, Meta!   Obviously, this helps Akira move the ball down the field too.

**Comment by gmao-msienkie** [comment] 2022-08-12 14:08
> Is `wind_reduction_factor_at_10m` something that would come in the PREPBUFR? If not I wonder if we should be recomputing `wind_reduction_factor_at_10m` in JEDI. So we don't end up having to revisit this when we start going from BUFR instead of NCDiags for the JEDI obs.

No, the information to obtain this is not in the PREPBUFR, it is obtained from the background fields and then the 'factw' is scaled based on the distance above the surface and below the first model level.  If the observation height is above the height of the first model level this factor is set to 1.

**Comment by gthompsnJCSDA** [comment] 2022-08-17 15:54
Good catch everyone!  Yes during take-offs and landings, I suspect that factw has a role to play - although I would be quite surprised these winds are being put into the DA as actual used winds.  As a meteorologist, there's no way I trust the airplane winds within the typical Delta-Z of between surface and 1st model level considering the *vast* majority of airports also report the winds at 10 meters.  The quality of obs that near the ground from aircraft is too suspicious in my own opinion.  But getting a match is getting a match and usage can be a separate issue.

**Comment by gthompsnJCSDA** [comment] 2022-08-17 16:00
BTW, I would be more hesitant to include factw into SatWinds - *OTHER* than the ASCAT or sea-surface winds, because I cannot imagine that satellite-derived AMVs are being used operationally within about 100hPa of the surface.  I was pretty shocked when I saw the number of obs being rejected either near the surface or low levels in general within the GDAS.  However, since there is effectively no harm in setting this ```use_fact10``` for any winds whatsoever, I guess it can be thrown in everywhere.

**Comment by danholdaway** [comment] 2022-08-17 16:28
@gthompsnJCSDA we need this to replicate the behavior of GSI for all conventional, satwinds, raobs, aircraft etc. In gsi whenever a wind observation is below the lowest model level it needs to be scaled to replicate GSI. We'll work on an implementation in AtmVertInterp for now. Though perhaps it should be a filter? Whatever we do it will be non-intrusive and off by default.

**Comment by gthompsnJCSDA** [comment] 2022-08-17 17:09
Dan, I am a bit lost. Is ```use_fact10``` only available via GSISfcModel or is it also an option in VertInterp?  Should be pretty quick to copy code from the one to other if not already there.

**Comment by danholdaway** [comment] 2022-08-17 19:25
@gthompsnJCSDA we plan to add that feature also the AtmVertInterp operator.

**Comment by gmao-msienkie** [comment] 2022-08-17 21:18
Another issue with the aircraft bias correction is that the aircraft vertical velocity was not written to the nc4 diag file - the vertical velocity (ascent/descent rate) and squared vertical velocity would be needed as predictors for the aircraft bias correction that is being used in the current DAS.  That is another delay on the temperature implementation.

**Comment by danholdaway** [comment] 2022-08-17 22:50
@gmao-msienkie can we make the necessary changes to GSI ahead of the next rerun that @gmao-jjin3 would make?

**Comment by gmao-msienkie** [comment] 2022-08-18 05:11
> @gmao-msienkie can we make the necessary changes to GSI ahead of the next rerun that @gmao-jjin3 would make?
It should be an easy change in the GSI, I have example code.

**Comment by gmao-msienkie** [comment] 2022-08-18 17:29
> @gmao-msienkie can we make the necessary changes to GSI ahead of the next rerun that @gmao-jjin3 would make?

It should be an easy change in the GSI, I have example code.

**Comment by gmao-msienkie** [comment] 2022-08-30 19:36
> In order to match our GSI, the ObsErrorFactorConventional filter will need to be modified to work like the errormod_aircraft code with additional checks for horizontal distance between aircraft observations.

I was looking at the code in ObsErrorFactorConventional.cc and it appears there is a distance threshhold check if a parameter is set
float distthres = options_->distthreshold.value().value_or(0.0f);

**Comment by gmao-msienkie** [comment] 2022-08-31 13:42
> > @gmao-msienkie can we make the necessary changes to GSI ahead of the next rerun that @gmao-jjin3 would make?
> 
> It should be an easy change in the GSI, I have example code.

I have the one-line change added in the branch feature/msienkie/add_cft_vv_nc4

**Comment by gmao-jjin3** [comment] 2022-08-31 16:10
> > > @gmao-msienkie can we make the necessary changes to GSI ahead of the next rerun that @gmao-jjin3 would make?
> > 
> > 
> > It should be an easy change in the GSI, I have example code.
> 
> I have the one-line change added in the branch feature/msienkie/add_cft_vv_nc4

Thanks, Meta. I see the output is added in the develop branch as: 
`call nc_diag_metadata("Data_Vertical_Velocity", sngl(data(ivvlc,i))  )`

**Comment by gmao-jjin3** [comment] 2022-09-02 04:08
> 

Hi Meta, I was able to save this variable as _**data_vertical_velocity**_ in  
/discover/nobackup/jjin3//jedi/For_others/x0044.jj_20220901/conv/aircraft_tsen_obs_2020121500.nc4 
However, I couldn't find a tool to convert aircraft bias correction coefficient text files to NeCDF file. Here is an issue Andrew Collard discussed about it with his colleagues at EMC.
https://github.com/JCSDA-internal/ioda-converters/issues/804
I couldn't see any PRs to resolve this issue at the moment. @danholdaway  @gmao-yzhu

**Comment by gmao-msienkie** [comment] 2022-09-02 06:19
> 



> > 
> 
> Hi Meta, I was able to save this variable as _**data_vertical_velocity**_ in /discover/nobackup/jjin3//jedi/For_others/x0044.jj_20220901/conv/aircraft_tsen_obs_2020121500.nc4 However, I couldn't find a tool to convert aircraft bias correction coefficient text files to NeCDF file. Here is an issue Andrew Collard discussed about it with his colleagues at EMC. [JCSDA-internal/ioda-converters#804](https://github.com/JCSDA-internal/ioda-converters/issues/804) I couldn't see any PRs to resolve this issue at the moment. @danholdaway @gmao-yzhu

If you can copy the ana.acftbias file to your data area I can look at the issue when I start implementing the bias correction.

**Comment by gmao-jjin3** [comment] 2022-09-02 13:27
> > 
> 
> > > 
> > 
> > 
> > Hi Meta, I was able to save this variable as _**data_vertical_velocity**_ in /discover/nobackup/jjin3//jedi/For_others/x0044.jj_20220901/conv/aircraft_tsen_obs_2020121500.nc4 However, I couldn't find a tool to convert aircraft bias correction coefficient text files to NeCDF file. Here is an issue Andrew Collard discussed about it with his colleagues at EMC. [JCSDA-internal/ioda-converters#804](https://github.com/JCSDA-internal/ioda-converters/issues/804) I couldn't see any PRs to resolve this issue at the moment. @danholdaway @gmao-yzhu
> 
> If you can copy the ana.acftbias file to your data area I can look at the issue when I start implementing the bias correction.

Done. The file /discover/nobackup/projects/gmao/dadev/rtodling/archive/x0044/ana/Y2020/M12/x0044.ana.acftbias.20201214_18z.txt  is copied and renamed as aircraft_bias.20201214_15z.txt .

**Comment by rgelaro** [comment] 2022-09-02 14:01
Thank you, Jianjun.

**Comment by gmao-msienkie** [comment] 2022-09-21 18:26
A QC test was carried out with just the initial ObsError filters configured.  The values for these filters should match the values in the 'prepobs_errtable.global' file in the GSI.  With only the initial ObsError filters, the 'ObsError' values should match the values for 'GsiInputObsError'.  The values for u- and v- component wind matched.  Unfortunately the 'GsiInputObsError' field was not written to the input obs 'aircraft_tsen_obs_2020121500.nc4' so the accuracy of the initial temperature error assigned could not be readily assessed.  Also the test date did not contain any dropsonde (kx=132,232) data so those data types could not be assessed either.

**Comment by gmao-jjin3** [comment] 2022-09-21 20:46
Meta, here are lists of atmospheric conventional data kx values in the Converter. I added 132 and 232 for dropsonde data. Are there more changes do you see we need add? Thank you.   
```
conv_bufrtypes = {
    "aircraft": [130, 131, 133, 135],  # 234 is TAMDAR; always rstprod
#   "sondes": range(120, 123),
    "sondes": [range(120, 123), 132, 232],
    "rass": [126],
    "sfcship": [180, 183],
    "sfc": [181, 187],
#   "gps": [3, 4, 42, 43, 745, 825],
    "gps": [3, 4, 5, 42, 43, 44, 745, 750, 751, 752, 753, 825],

```

**Comment by gmao-msienkie** [comment] 2022-09-21 21:25
The issue with the dropsondes is that there were no 132/232 observations on 20201215/00z.  It is December and so not many tropical storms.  There are some a few days before and a few days after.  
https://gmao.gsfc.nasa.gov/intranet/science/gms/x0044/TERRA_html/obs2html/Y2020/M12/conv/G5/x0044.pseries.L5.2020120100-2020123118.png
So I think we could let the dropsonde go unless we run test cases on other days.

In the JEDI test files (e.g. ufo/test/testinput/instrumentTests/Aircraft_obs/aircraft_gfs_qc.yaml) they have included type RECON and dropsonde data types 132/232 in the aircraft qc tests, for what it is worth.   
So perhaps the "aircraft" could be range(130,135)

**Comment by gmao-msienkie** [comment] 2022-10-05 23:01
The aircraft_profl BUFR files have aircraft obs separated into multilevel records with ascent or descent profiles and other aircraft obs (e.g. at flight level) that are not part of an ascent or descent profile.  The 'errormod_aircraft' process is carried out record by record so that the possible multiple ascent and descent profiles are handled separately.  For the 'ObsErrorFactorConventional' filter we are currently only able to separate obs by "station ID" (tail number) so multiple profiles might be lumped together in the processing.  I thought perhaps if there were a 'Release time' or 'Launch time' available it could be used to separate the profiles (just as it would for the sonde data).  However the recently added 'Release time' is only written for sonde data so in order to use it, code would need to be added for aircraft data.

**Comment by rgelaro** [comment] 2022-10-06 13:57
Is this essentially what we realized needed to be done during yesterday's meeting?  Or does the assessment above indicate that the step(s) needed to have this information written into the file are more involved than we thought?

**Comment by gmao-msienkie** [comment] 2022-10-06 14:18
> Is this essentially what we realized needed to be done during yesterday's meeting? Or does the assessment above indicate that the step(s) needed to have this information written into the file are more involved than we thought?

It is a bit more involved than what I thought.  Jianjun had suggested that the launch time was only being written for radiosondes so I checked the code and found out he was correct.  The read_prepbufr.f90 code would need to be modified in order to fill in a value for launch time for aircraft data in place of the missing value that is currently written.

**Comment by rgelaro** [comment] 2022-10-06 15:01
Thanks.  Also, are we sure that the launch time information, were it to be written for aircraft, would provide the information needed to distinguish the ascent/descent and flight-level observations as needed?  I think I recall that we needed to confirm this first, but perhaps not.

**Comment by gmao-jjin3** [comment] 2022-10-06 16:48
Thank you, Meta.  I have a look at the reading code. The "lauchtime" may be saved during reading the Prepbufr and eventually written in NetCDF files by changing one line:
```
diff /discover/nobackup/jjin3/GEOSadas_git/GEOSadas/src/Components/@GEOSana_GridComp/GEOSaana_GridComp/GSI_GridComp/read_prepbufr.f90_20220715 /discover/nobackup/jjin3/GEOSadas_git/GEOSadas/src/Components/@GEOSana_GridComp/GEOSaana_GridComp/GSI_GridComp/read_prepbufr.f90
1806c1806
<               time_launch=-99999.0_r_kind
---
>               time_launch=time
```    
How do you think?

**Comment by gmao-msienkie** [comment] 2022-10-06 19:43
No, I don't think that will work.  We need to use one time for all of the observations in an aircraft report, and I think that time should be based on the DHR value in the header.  That would be hdr(4), which is read in at around line 941.    The obs without  drift information use hdr(4) to get 'time' (from timeobs).  The aircraft and sonde/pibal use the drift time to define 'time'.  I need to check more carefully if the other obs are impacted by 'errormod' and would even need time_launch.

You could move up the time_launch initialization above the aircraft block, then define time_launch in that aircraft block based on DHR.  Unfortunately that variable hdr is reused for ACARS obs around line 1497 so that code would also need to be modified so 'hdr' doesn't get clobbered.  You could also use the first level drift time as is done for the raobs though I don't like that as much - for descending obs that would be the last time in the profile rather than the first time.  

(As an aside I can see why it makes sense to use the first obs level drift time for raobs because of possibly arbitrary adjustments for DHR in the raob processing, while in the aircraft profile processing it looks like the DHR matches the earliest time in the profile.)

**Comment by gmao-jjin3** [comment] 2022-10-06 19:48
Thanks, Meta!

**Comment by gmao-jjin3** [comment] 2022-10-07 17:40
Hi Meta, Here are changes I made following your suggestions
```
>   real(r_double),dimension(1):: hdracid
1497,1498c1498,1499
<               call ufbint(lunin,hdr,1,1,iret,'ACID')
<               if(ibfms(hdr(1))==0) rstation_id=hdr(1)
---
>               call ufbint(lunin,hdracid,1,1,iret,'ACID')
>               if(ibfms(hdracid(1))==0) rstation_id=hdracid(1)
1777a1779,1780
>               time_launch=-99999.0_r_kind
> 
1805a1809
>                  time_launch=real(real(hdr(4),r_single),r_double) + time_correction
1812,1813d1815
< 
<               time_launch=-99999.0_r_kind

```
It is easier to see them by "xxdiff":
`xxdiff /discover/nobackup/jjin3/tmp/GEOSadas/src/Components/@GEOSana_GridComp/GEOSaana_GridComp/GSI_GridComp/read_prepbufr.f90_20220929  /discover/nobackup/jjin3/tmp/GEOSadas/src/Components/@GEOSana_GridComp/GEOSaana_GridComp/GSI_GridComp/read_prepbufr.f90
`
I didn't have a clue to get the "initial launch time" for descending flights.

**Comment by gmao-msienkie** [comment] 2022-10-07 19:49
I'm sorry.  I already modified the read_prepbufr.f90 myself and put in a branch on Github and meant to post here, but I was distracted by a question in my email.    The branch is feature/msienkie/aircraft_time_launch - though unfortunately I have a bunch of whitespace removed which puts in more diffs.

I have a printout of data from the aircraft profile file from 20201215/00z in
/discover/nobackup/msienkie/cftbias//src/ckcft_tmp/acft.20201215.t00z.AIRCAR
/discover/nobackup/msienkie/cftbias//src/ckcft_tmp/acft.20201215.t00z.AIRCFT

You can see in the printout that the earliest time in the ascending or descending profiles is the same as in DHR in the header (although I only printed the profile time to 2 decimal places)

It looks like your patch is more or less what I did as well.  I didn't have a chance to run this since I don't have a build from a recent tag that I am able to run.

**Comment by gmao-jjin3** [comment] 2022-10-07 20:54
No problem at all. I'll take a look at your branch and your printout. I can build and run a test. Thanks again.

**Comment by gmao-jjin3** [comment] 2022-10-11 13:33
Hi Meta,
Here are new aircraft data with the variable "LaunchTime" in /discover/nobackup/jjin3/jedi/For_others/x0044.jj_20221009/conv/
aircraft_tsen_obs_2020121500.nc4
aircraft_tsen_geoval_2020121500.nc4
aircraft_uv_obs_2020121500.nc4
aircraft_uv_geoval_2020121500.nc4

**Comment by danholdaway** [comment] 2022-10-11 16:21
@gmao-msienkie @gmao-jjin3 I've run the combine tool to make single aircraft_obs and aircraft_geoval files. These replace the old files at `/discover/nobackup/drholdaw/JediUfoTests/Data/ufo/testinput_tier_1/instruments/conventional` . I see that you've called it `LaunchTime`. Should it perhaps be `launch_time` to match the convention in the naming of other variables?

**Comment by gmao-jjin3** [comment] 2022-10-11 16:54
@danholdaway  I agree. But, that is the name in the converter "gsi_ncdiag.py".  We may need update someone else's Yaml or programs if we rename it.

**Comment by gmao-msienkie** [comment] 2022-10-11 17:16
The sondes file also has LaunchTime and several of the sonde test yaml files use it.  I wouldn't worry about it now.

**Comment by gmao-msienkie** [comment] 2022-10-19 20:09
The ObsErrorFactorConventional results were improved after adding the filter to reject obs with input prepbufr QC mark > 8.  Tests are done with only initial obs error and ObsErrorFactorConventional applied and EffectiveQc results compared to GsiInputObsError. There are still some inconsistencies to investigate - one set of obs with the GSI error 10x the initial error and other obs with larger Jedi obs errors.
![corscat_eferr_vs_adjer](https://user-images.githubusercontent.com/53273921/196793529-21938213-0a6b-46e7-bb47-200ea50d4b1c.png)

**Comment by gmao-msienkie** [comment] 2022-10-26 20:05
Implemented filter to inflate obs error 10x for type 130 if pressure > 500hPa.  (Technically only should apply if using aircraft_t_bc varBC but we are using that in GSI.)  This moved the stray point in lower left corner of the comparison and improved the line fit.
![corscat_eferr_vs_adjer](https://user-images.githubusercontent.com/53273921/198125938-cd42a86e-4f08-46f7-a366-cfe01e15bd09.png)

**Comment by gmao-msienkie** [comment] 2023-01-24 18:59
I found that in some cases observations treated as single level data in the GSI (and not subject to 'errormod' error inflation) can have the same station ID and release time - and will be treated as profile data by the ObsErrorFactorConventional filter in the UFO.  This explains some of the cases where the error values produced in my UFO tests are different from those in the GSI.

Here some examples of near-duplicate data from one tail number written as single-level data in the aircraft_profile file that was read in to our x0044 case:

SID=LXHVGABA, YOB= 66.88,XOB=200.12, ELV=11887.0, DHR= 2.700, TYP= 333., NLEV=   1
SID=LXHVGABA, YOB= 66.92,XOB=200.05, ELV=11887.0, DHR= 2.700, TYP= 333., NLEV=   1
SID=LXHVGABA, YOB= 66.85,XOB=200.19, ELV=11888.0, DHR= 2.700, TYP= 333., NLEV=   1

SID=MBVFGARA, YOB= 60.56,XOB=213.12, ELV= 9143.0, DHR=-1.350, TYP= 333., NLEV=   1
SID=MBVFGARA, YOB= 60.57,XOB=213.05, ELV= 9147.0, DHR=-1.350, TYP= 333., NLEV=   1
SID=MBVFGARA, YOB= 60.58,XOB=212.99, ELV= 9149.0, DHR=-1.350, TYP= 333., NLEV=   1

SID=OWJVGABA, YOB= 40.68,XOB=283.82, ELV=10362.0, DHR=-0.767, TYP= 333., NLEV=   1
SID=OWJVGABA, YOB= 40.68,XOB=283.86, ELV=10363.0, DHR=-0.767, TYP= 333., NLEV=   1
SID=OWJVGABA, YOB= 40.67,XOB=283.77, ELV=10367.0, DHR=-0.767, TYP= 333., NLEV=   1

The 'GsiAdjustObsError' for these data is the same as the 'GsiInputObsError', but in the UFO the errors are inflated by the ObsErrorFactorConventional filter.  Given their proximity I suppose the error inflation would be justified.

**Comment by gmao-msienkie** [comment] 2023-01-25 18:13
another example:
SID=JP9Z4U66,YOB= 34.78,XOB=135.42,ELV=   31.0,DHR= 0.000,TYP= 231.,NLEV=   1
SID=JP9Z4U66,YOB= 34.78,XOB=135.42,ELV=   61.0,DHR= 0.000,TYP= 231.,NLEV=   1
SID=JP9Z4U66,YOB= 34.78,XOB=135.42,ELV=   91.0,DHR= 0.000,TYP= 231.,NLEV=   1
SID=JP9Z4U66,YOB= 34.78,XOB=135.42,ELV=  122.0,DHR= 0.000,TYP= 231.,NLEV=   1
SID=JP9Z4U66,YOB= 34.78,XOB=135.42,ELV=  152.0,DHR= 0.000,TYP= 231.,NLEV=   1
SID=JP9Z4U66,YOB= 34.78,XOB=135.42,ELV=  213.0,DHR= 0.000,TYP= 231.,NLEV=   1
SID=JP9Z4U66,YOB= 34.80,XOB=135.42,ELV=  250.0,DHR= 0.000,TYP= 231.,NLEV=   1
SID=JP9Z4U66,YOB= 34.80,XOB=135.41,ELV=  402.0,DHR= 0.000,TYP= 231.,NLEV=   1
SID=JP9Z4U66,YOB= 34.80,XOB=135.40,ELV=  555.0,DHR= 0.000,TYP= 231.,NLEV=   1

I'm not sure why these didn't get put into a profile in the input file.

**Comment by gmao-jjin3** [comment] 2023-01-25 18:55
It is possible that these aircraft data files are not combined properly? Here is the program
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/gsi-ncdiag/combine_obsspace.py
CC  @CoryMartin-NOAA @danholdaway

**Comment by gmao-msienkie** [comment] 2023-01-25 19:29
> It is possible that these aircraft data files are not combined properly? Here is the program https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/gsi-ncdiag/combine_obsspace.py CC @CoryMartin-NOAA @danholdaway

No.  The issue is that we thought we could group profiles as multiple obs with same stationIdentification and same releaseTime.  From my printout above I found single level obs (NLEV=1) that had the same ID and same releaseTime(DHR) that would be processed as profile data by ObsErrorFactorConventional but were not processed by errormod_aircraft in the GSI.

**Comment by gmao-msienkie** [comment] 2023-02-14 21:25
I copied the configuration for the pressure check function from Jianjun's sonde configuration and added it to my aircraft_geos_qc.yaml file and ran a test.  Of course, since the bias correction has not been applied yet, the bias corrected H(x) and the number of observations passing QC will not match.  With the GSIAdjustObsError used in place of the adjusted UFO error (i.e. after ObsErrorFactorConventional) and the pressure check function applied there are still differences from the GSI final obs error due to the duplicate factor not being applied:
![corscat_eferr_vs_finaler](https://user-images.githubusercontent.com/53273921/218866019-ef918116-3ca0-444a-aeef-9a8a3d3682a5.png)
However just as for the radiosonde virtual temperature, the error for the aircraft temperature matches the GSI final error if the duplicate factor written out from the GSI is applied.
![corscat_eferr_x_GsiDup_vs_finaler](https://user-images.githubusercontent.com/53273921/218866541-7a513222-3100-482c-bdc6-28c29daea4d2.png)

**Comment by rgelaro** [comment] 2023-02-14 21:31
Thanks, Meta.  This is encouraging.  We'll pick it up tomorrow.

Ron
________________________________
From: Meta Sienkiewicz ***@***.***>
Sent: Tuesday, February 14, 2023 4:25 PM
To: GEOS-ESM/swell ***@***.***>
Cc: Gelaro, Ronald (GSFC-6101) ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/swell] YAML Configuration | Aircraft (Issue #60)


I copied the configuration for the pressure check function from Jianjun's sonde configuration and added it to my aircraft_geos_qc.yaml file and ran a test. Of course, since the bias correction has not been applied yet, the bias corrected H(x) and the number of observations passing QC will not match. With the GSIAdjustObsError used in place of the adjusted UFO error (i.e. after ObsErrorFactorConventional) and the pressure check function applied there are still differences from the GSI final obs error due to the duplicate factor not being applied:
[corscat_eferr_vs_finaler]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F53273921%2F218866019-ef918116-3ca0-444a-aeef-9a8a3d3682a5.png&data=05%7C01%7Cronald.gelaro-1%40nasa.gov%7Cedd1806c20fc450fee4008db0ed20f65%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638120067585163286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2MfgV73XXo1qpXbzIAoFakLvAmdxt%2BLxVb5CYU5pAqU%3D&reserved=0>
However just as for the radiosonde virtual temperature, the error for the aircraft temperature matches the GSI final error if the duplicate factor written out from the GSI is applied.
[corscat_eferr_x_GsiDup_vs_finaler]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F53273921%2F218866541-7a513222-3100-482c-bdc6-28c29daea4d2.png&data=05%7C01%7Cronald.gelaro-1%40nasa.gov%7Cedd1806c20fc450fee4008db0ed20f65%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638120067585163286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9o1%2BLek51Ck6W8FG5CxuL4KE6WuOdMyC6xm%2Fn%2BX9p5I%3D&reserved=0>

**Comment by gmao-msienkie** [comment] 2023-02-22 19:32
Density plots for UFO using output from GSI run with no aircraft temperature bias correction 
![density_qc_omb_vs_gsiomb](https://user-images.githubusercontent.com/53273921/220739019-23ec821d-8478-43d6-8ee4-0a44683eedc8.png)
![density_qc_omb_vs_gsiombbc b](https://user-images.githubusercontent.com/53273921/220739056-ec7cfba5-6379-4b7a-b3ad-b428fde4a66a.png)
![density_qc_omb_vs_gsiombbc](https://user-images.githubusercontent.com/53273921/220739078-b7be9a95-030c-4a51-8a58-947567b28942.png)

**Comment by gmao-msienkie** [comment] 2023-03-01 15:12
Test with aircraft bias correction applied: temperature error matches (almost)

![corscat_eferr_vs_finaler](https://user-images.githubusercontent.com/53273921/222180723-dc4763b4-e257-4af0-bea5-2da53996cb9d.png)

**Comment by gmao-msienkie** [comment] 2023-03-01 17:01
The difference in GSI Final Obs error and JEDI effective error for temperature was less than 0.05K except for 15 observations from stationID 'RPXTOZBA'.  A check of the input aircraft temperature bias correction file found that the bias coefficients were uninitialized for this stationID/tail number, and tails with uninitialized coefficients (all values equal to zero) have errors inflated by a factor of 1.2 by the GSI.  A check for this can be added to the aircraft YAML file when the bias coefficient data becomes available.

**Comment by gmao-msienkie** [comment] 2023-03-15 15:29
Plot of difference in GSI Final Obs error and JEDI effective error for temperature.  The 15 observations with a discrepancy in the error show up as the dot in the upper left of the plot.
![corscat_eferrdiff_vs_eferr](https://user-images.githubusercontent.com/53273921/225359039-a60ef0e6-ac56-415e-9a29-62e0801b13ba.png)

**Comment by gmao-msienkie** [comment] 2023-03-15 15:36
New density plot for aircraft temperature from run with no bias correction - with both stats on the plot.  'GSIEffectiveQC = 0' is used to determine which GSI obs passed QC.
![density_qc_omb_vs_gsiomb](https://user-images.githubusercontent.com/53273921/225361508-3d70df54-3de7-4cfe-a4af-a1ed7fc8ca46.png)

**Comment by gmao-msienkie** [comment] 2023-03-15 20:13
Working with a new build with jedi_bundle version 1.0.8.  I merged the develop branch into Wei's branch and rebuilt.  After a couple of iterations, it looks like the aircraft winds are working in the UFO.  The number of obs passing QC now match in GSI and UFO.

![corscat_eferr_vs_finaler](https://user-images.githubusercontent.com/53273921/225431122-719f3063-3d54-46c9-a5b3-e66a2ab0ded7.png)
![corscat_eferrdiff_vs_eferr](https://user-images.githubusercontent.com/53273921/225431141-cf9a4cba-80ef-4ab0-88d1-1da07d24a2e3.png)
![corscat_hofx_vs_gsihofx](https://user-images.githubusercontent.com/53273921/225431323-aeaf23d9-3016-4dcc-b110-8b23fe5d9d24.png)
![corscat_hofxdiff_vs_gsihofx](https://user-images.githubusercontent.com/53273921/225431196-f9805984-fd59-405c-a366-628337a0fa49.png)
![density_qc_omb_vs_gsiomb](https://user-images.githubusercontent.com/53273921/225431446-d260ee14-e46e-416c-8b68-8b907408f542.png)

**Comment by gmao-msienkie** [comment] 2023-04-12 18:28
The JediEffectiveError matches the GSIFinalObsError if we substitute the GSI Adjusted obserror in place of UFO error after applying ObsErrorFactorConventional.  If ObsErrorFactorConventional is used, there are discrepancies for some observations but the obs errors for over 96% of the u-component have differences less than 0.05 m/s.  Some observations read into GSI as 'single level' have the same obs time and so they are grouped as members of profiles in UFO.  These obs would have larger obs errors assigned in UFO.  Some observations have small error differences that result from slightly different model pressure levels used in the errormod in GSI (center time pressure levels) versus the UFO ObsErrorFactorConventional (interpolated obs time values from geovals).
![corscat_eferrdiff_vs_eferr](https://user-images.githubusercontent.com/53273921/231551116-03cfc9b1-ee87-48d8-90c1-943f8fa6e138.png)
![corscat_eferrdiff_vs_eferr](https://user-images.githubusercontent.com/53273921/231551159-cbbf685c-a3ec-48fa-a753-ac81651f832f.png)

**Comment by gmao-msienkie** [comment] 2023-06-29 16:55
I noticed this issue regarding implementation of 'offline' aircraft temperature bias correction 
https://github.com/NOAA-EMC/JEDI-T2O/issues/65

**Comment by CoryMartin-NOAA** [comment] 2023-06-29 16:58
@gmao-msienkie yes we are almost done with that, @bretthoover-noaa is working on the converter from GSI abias_air to JEDI CSV now

**Comment by gmao-msienkie** [comment] 2023-08-02 17:59
A test of the aircraft temperature HofX with bias correction using the 2021 data shows that the bias-corrected UFO HofX matches the GSI bias corrected HofX.  
![corscat_hofxdiffbc_vs_gsihofxbc](https://github.com/GEOS-ESM/swell/assets/53273921/012eb1d3-5939-49db-a7fd-644eae04304a)

**Comment by gmao-msienkie** [comment] 2023-08-09 20:37
There were 46 observations in the 2021 case that had had a discrepancy in the GSI Final Obs error vs JEDI effective error for temperature.  Now that the bias coefficients have been read in (via DrawValueFromFile) we can add a test for tails with uninitialized bias coefficients (missing or all coeffs = 0) - the obs error for tails with uninitialized coefficients is inflated by 1.2.  This test is able to adjust the error for the 46 observations and remove the discrepancy.

![corscat_eferrdiff_vs_eferr](https://github.com/GEOS-ESM/swell/assets/53273921/61443913-8663-4869-9fde-a38232425b9d)

**Comment by gmao-msienkie** [comment] 2023-08-09 20:43
The number of obs accepted by QC in UFO vs GSI differed by 1.  This was resolved by adjusting the Background Check to use the bias corrected HofX - test_hofx: HofXBc .
![density_qc_ombbc_vs_gsiombbc](https://github.com/GEOS-ESM/swell/assets/53273921/0bde9c7e-5129-4d79-8ddd-c3b59641e4a7)

**Closed as completed** 2023-09-22 16:40 UTC
