### ISSUE TITLE
YAML Configuration | AIRS

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#61] opened 2022-05-12 16:37 UTC
## Agreement with GSI using GeoVaLs in UFO (Hofx no bias correction)

- [x] AQUA

## Agreement with GSI using GeoVaLs in UFO (Bias correction)

- [x] AQUA

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] AQUA

## Agreement with GSI using GeoVaLs in UFO (Hofx with bias correction)

- [x] AQUA

## Agreement with GSI using Swell

- [ ] AQUA

## Pull requests in JEDI

- [ ] [Pull request being prepared for UFO and UFO-data](https://github.com/JCSDA-internal/ufo/pull/2166)

## Current issues:

- Notes:  For short-wave channels with wavenumber between 2000 and 2400, the number of observations passing QC does not match between the GSI and UFO, which is caused by a wrong handling in the GSI by assigning a non-zero QC mark(51) for observations that are still being assimilated, so we can not draw conclusion simply based on qc=0 in this case.  If we combine the number of observations with qc=0 and and the number of observations with qc=51 in the GSI, the total number does match the number of observations with qc=0  in the UFO.

**Comment by gmao-wgu** [comment] 2022-08-17 21:00
For AIRS long-wav(LW) temperature channels and mid-wave water-vapor channels, the consistency between the GSI and UFO can be achieved,  which can be demonstrated from the following plots by using ch006(LW temperature) and ch212(Mid-Wave water-vapor) as examples:

![airs_aqua Swell_Obs_Number O-F_BC_QC ch006 ps](https://user-images.githubusercontent.com/59488002/185240664-861adddd-65fd-4687-9410-9e361b87b2a5.png)
![airs_aqua Swell_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch006 ps](https://user-images.githubusercontent.com/59488002/185240713-15bda7ce-df0a-416d-a007-89952fbd40de.png)
![airs_aqua Swell_EffectiveError GsiFinalObsError_QC ch006 ps](https://user-images.githubusercontent.com/59488002/185240747-abb8d4bd-42ea-48ea-badb-c5c89f9134d8.png)
![airs_aqua Swell_Obs_Number O-F_BC_QC ch212 ps](https://user-images.githubusercontent.com/59488002/185241437-0b4689bd-aee2-4692-8f06-cb18e8f13ee3.png)
![airs_aqua Swell_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch212 ps](https://user-images.githubusercontent.com/59488002/185241467-7bdf5665-89e6-41b7-988f-040d02c0b8eb.png)
![airs_aqua Swell_EffectiveError GsiFinalObsError_QC ch212 ps](https://user-images.githubusercontent.com/59488002/185241504-14779954-1e83-4fb5-8e88-d8e58015b6a1.png)

**Comment by gmao-wgu** [comment] 2022-08-17 21:36
@gmao-jjin3 @danholdaway @gmao-yzhu
However, some short-wave temperature channels from AIRS are also assimilated in the GEOS. For those channels, the number of obs passing QC seems not matched between the GSI and UFO which can be seen from the following plot by using channel 227 as an example:
![airs_aqua Swell_Obs_Number O-F_BC_QC ch227 ps](https://user-images.githubusercontent.com/59488002/185243653-e1c32327-d539-47d8-889b-1b17d474a33b.png)
Much more observations seem to be able to pass QC in UFO than in the GSI.  After checking the code carefully, it was found that this mismatch might be not what it looked like. In the GSI, shortwave check was implemented to apply to IR short-wave channels.  For those channels with wavenumber between 2000 and 2400, the observation errors were inflated and in the meantime a qc flag value of 51 was assigned to those observations. Therefore, for this non-zero flag of 51,  IR observations are still assimilated in the GSI, but are not counted in the plot because their qc values are not equal to zero. To further demonstrate this is the case, QC flags are plotted in the following:
![airs_aqua Swell_EffectiveQC GsiEffectiveQC ch227 ps](https://user-images.githubusercontent.com/59488002/185246911-7053c509-9930-41b0-97f4-8b791548b7b1.png)
It can be seen that the mismatch was exactly caused by qc flag 51 used in GSI. So if we plot qc=0 and qc=51 for both the GSI and UFO, I believe we should be able to get identical numbers because 51 was not used in UFO when inflating errors for short-wave observations with wavenumber between 2000 and 2400.

**Comment by gmao-jjin3** [comment] 2022-08-18 04:10
Wei, can you re-plot the histogram figure?  I've update my plotting program. Now, it checks "GsiFinalObsError" which  should be a positive finite number for an actively assimilated observation.

**Comment by gmao-wgu** [comment] 2022-08-18 14:33
> Wei, can you re-plot the histogram figure? I've update my plotting program. Now, it checks "GsiFinalObsError" which should be a positive finite number for an actively assimilated observation.

Thanks. I will give it a try.

**Comment by gmao-wgu** [comment] 2022-08-18 15:18
@gmao-jjin3 @danholdaway @gmao-yzhu 
**This is what I got from my replotting(qc=0 plus qc=51).**
![airs_aqua Swell_Obs_Number O-F_BC_QC ch227 ps (1)](https://user-images.githubusercontent.com/59488002/185430951-f2690bdc-fc1d-4818-a71a-e727b1ddf1cf.png)
**It is not correct in the GSI to assign a non-zero qc mark for observations we are still assimilating. We should get that fixed.**

**Closed as completed** 2023-09-22 16:40 UTC
Labels: ufo done
