### ISSUE TITLE
YAML Configuration | IASI

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#68] opened 2022-05-12 16:39 UTC
## Agreement with GSI using GeoVaLs in UFO (Hofx no bias correction)

- [x] Metop-A
- [x] Metop-B

## Agreement with GSI using GeoVaLs in UFO (Bias correction)

- [x] Metop-A
- [x] Metop-B

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] Metop-A
- [x] Metop-B

## Agreement with GSI using GeoVaLs in UFO (Hofx with bias correction)

- [x] Metop-A
- [x] Metop-B

## Agreement with GSI using Swell

- [ ] Metop-A
- [ ] Metop-B

## Notes:

It wasn't possible to get an exact match between the number of observations passing QC. Inside the CRTM interface there is a change in the surface quantities (https://github.com/GEOS-ESM/swell/issues/68#issuecomment-1155460871). The error inflation is calculated using the values before this conversion, while h(x) is computed using the values after the conversion. GSI writes the GeoVaLs after the conversion and this is all that UFO has. So UFO computes error inflation and h(x) using the values after the conversion. It would be complication to modify both GSI and UFO to write and then use values before and after conversion. Since in the end the YAML is correct and would not be altered by producing different test data we can consider the effort to produce configuration for IASI complete. It should be noted that even in Swell UFO will only get one set of GeoVaLs so wont mimic the GSI behavior. Perhaps this is OK since what the GSI does seems to be inconsistent in the sense that error inflation and h(x) are computed using potentially different surface types.

## Pull requests in JEDI

- [ ] [Pull request being prepared for UFO and UFO-data](https://github.com/JCSDA-internal/ufo/pull/2166)
- [ ] https://github.com/JCSDA-internal/ioda-converters/pull/921

**Comment by gmao-wgu** [comment] 2022-06-08 17:17
**Bugs found and fixed in _NearSSTRetCheckIR.cc_, _ObsErrorFactorSurfJacobianRad.h_ and _ObsErrorFactorSurfJacobianRad.cc_. Impacts of the fixes on QC can be shown in the following figures.**
 **For Window Channels:**  
**Before Fixes**
![iasi_metop-a Swell_Obs_Number O-F_BC_QC ch180 ps](https://user-images.githubusercontent.com/59488002/172672841-61dc4d7f-4de8-4aa3-b695-571af7e25b84.png)
**After Fixes**:
![iasi_metop-a Swell_Obs_Number O-F_BC_QC ch180 ps (1)](https://user-images.githubusercontent.com/59488002/172673289-a11966c2-0d7e-4d9c-bdcb-6bd26a277081.png)
**From the following figure we could see that Jedi effective qc flag with the value of 0 is one to one matched with gsi effective qc flag of 0**.
![iasi_metop-a Swell_EffectiveQC GsiEffectiveQC ch180 ps (1)](https://user-images.githubusercontent.com/59488002/172737393-7f2b4a71-148a-4da2-891a-839dd33e3d4d.png)

**For Ozone Channels**:
**Before Fixes**:
![iasi_metop-a Swell_Obs_Number O-F_BC_QC ch266 ps](https://user-images.githubusercontent.com/59488002/172674244-b663bd8f-2b6d-4078-a0d8-ac2a5766ca31.png)
**After Fixes:**
![iasi_metop-a Swell_Obs_Number O-F_BC_QC ch266 ps (1)](https://user-images.githubusercontent.com/59488002/172674850-baa757b2-ac5a-47e3-a103-1b94e027936d.png)
![iasi_metop-a Swell_EffectiveQC GsiEffectiveQC ch266 ps](https://user-images.githubusercontent.com/59488002/172738435-b182693b-982c-4927-b95f-6235b035a267.png)
**Points (61,0),(62,0),(63,0) and (65,0) in the above plot indicate that observations from ozone channels that can pass Jedi QC are all over non-water surface types but rejected by GSI QC.** 
 
**Issues Remaining**:
1) **Still a couple of points in which effective errors from Jedi do not match with those from the GSI,  Needs to double check error inflation part of QC filters in Jedi.**
![iasi_metop-a Swell_EffectiveError GsiFinalObsError_QC ch180 ps](https://user-images.githubusercontent.com/59488002/172675817-21b10f0c-c53b-4b1a-bffd-7513f7476970.png)
  2) **There is no filter in place in Jedi to reject ozone channels over non-water surface types, that is, need to convert this part of code in GSI into a filter in JEDI**

``` fortran
      do i = 1, nchanl
           m =  ich(i)
           if(iwater_det(m) > 0 .and. sea) then
              varinv(i) = zero
              if(id_qc(i) == igood_qc)id_qc(i)=ifail_iwater_det
           endif
           if(isnow_det(m) > 0 .and. snow) then
              varinv(i) = zero
              if(id_qc(i) == igood_qc)id_qc(i)=ifail_isnow_det
           endif
           if(mixed .and. imix_det(m) > 0) then
              varinv(i) = zero
              if(id_qc(i) == igood_qc)id_qc(i)=ifail_imix_det
           endif
           if(land .and. iland_det(m) > 0) then
              varinv(i) = zero
              if(id_qc(i) == igood_qc)id_qc(i)=ifail_iland_det
           endif
           if(ice .and. iice_det(m) > 0) then
              varinv(i) = zero
              if(id_qc(i) == igood_qc)id_qc(i)=ifail_iice_det
           endif
        enddo
```

**Comment by danholdaway** [comment] 2022-06-08 17:21
Great stuff @gmao-wgu!

**Comment by gmao-wgu** [comment] 2022-06-13 16:38
**It was found that only one location has the discrepancy between jedi and the GSI in terms of the effective observations error.  In the GSI, this location was treated over land surface type while in the Jedi it was treated over ice surface type. Because the surface Jacobian check applied inflates observation error differently over different surface types, thus the final effective errors are different.**

![EffectiveError_GSImJedi_ch515](https://user-images.githubusercontent.com/59488002/173402225-76805b71-483e-4889-942d-ebd4816fbadb.png)

**Comment by danholdaway** [comment] 2022-06-13 16:55
Good detective work. I would have thought the surface type was determined from the GeoVaLs, but wouldn't they be identical between the two runs being compared?

**Comment by gmao-wgu** [comment] 2022-06-13 17:13
ioda converter reads in the surface type fractions which are the values from the GSI analysis after one outer-loop, I guess somehow GSI analysis modified the surface type fraction at that location.

**Comment by gmao-wgu** [comment] 2022-06-13 17:52
I need to check with @gmao-jjin3  to see how this happened. @gmao-jianjun

**Comment by danholdaway** [comment] 2022-06-13 18:07
Yeah, it might require further discussion. It seems like an unlikely location for ice. The points on the plot do not appear to be organized like a satellite track. Is that expected?

**Comment by gmao-wgu** [comment] 2022-06-13 18:17
The points on the plot are in the satellite track:

![EffectiveError_GSImJedi_ch515_global](https://user-images.githubusercontent.com/59488002/173418335-d082029a-6a61-4793-bfdb-33933541b8b6.png)

**Comment by danholdaway** [comment] 2022-06-13 18:22
Thanks for the clarification.

**Comment by gmao-jjin3** [comment] 2022-06-13 18:38
> ioda converter reads in the surface type fractions which are the values from the GSI analysis after one outer-loop, I guess somehow GSI analysis modified the surface type fraction at that location.

Wei, I am not sure that is the case. Not sure why. However, can you print out ice_fraction and land fraction at this spot in JEDI and GSI?  Make sure the discrepancy is because of surface type change.

**Comment by gmao-wgu** [comment] 2022-06-13 18:46
I did print out in Jedi @gmao-jjin3 , the followings are what I got:
     latitude: 34.0224
     longitude: 279.133
     location: 4900
     obserror = 0.699445
    out = 6.61471
    water_frac=   0
    land_frac=   0
    ice_frac=   1
    snow_frac=   0
    dbtdes = 47.0935
    dbtdts = 0.79016
    demisf= 0.03
    dtempf = 4
so could you print out yours in the GSI? Note that the index in the sequence of observations should be 4901, channel index should be 180 out of 616 in the GSI.

**Comment by gmao-wgu** [comment] 2022-06-13 18:52
I calculated the error inflation value by hand based on these numbers, the surface type at this location should be land in the GSI @gmao-jjin3

**Comment by gmao-jjin3** [comment] 2022-06-13 19:05
@gmao-wgu  Can you point me where is your UFO output file?  I just need it in my program.

**Comment by gmao-wgu** [comment] 2022-06-13 19:08
ctest.j.o59230426_mismatch under /discover/nobackup/wgu/jedi_build/build-intel-impi-release/ufo. please search for "location" for those printout @gmao-jjin3

**Comment by gmao-jjin3** [comment] 2022-06-13 21:25
Wei:  The Land_Fraction is 0.00 in both original GSI output and the geoval file.
in /archive/u/jjin3/x0044j/obs/Y2020/M12/D15/H00/x0044j.diag_iasi_metop-a_ges.20201215_00z.nc4
Latitude=      34.0224
Longitude=      279.133
Land_Fraction=      0.00000
Ice_Fraction=      1.00000

/discover/nobackup/jjin3/jedi/For_others/x0044j/gsidiag_2_ufo/ncdiag/geovals/x0044j/PT6H/2020-12-15/iasi_metop-a_geoval_2020121500.nc4
Latitude=      34.0224
Longitude=      279.133
Land_area_Fraction=      0.00000
Ice_area_Fraction=      1.00000

**Comment by gmao-wgu** [comment] 2022-06-13 21:53
It is so strange @gmao-jjin3.  Could you please print out the values of other 2 parameters: emissivity_k, ts immediately after call qc_irsnd in the subroutine of setuprad.f90 at this location of (34.0224, 279.133) and i =180? Based on these two values, I could evaluate the error inflation by hand.

**Comment by gmao-wgu** [comment] 2022-06-13 22:01
@gmao-jjin3 Is it possible that inside GSI the value of ice_fraction is not 1 at this location?

**Comment by gmao-jjin3** [comment] 2022-06-14 01:29
Wei, all the test data come from the first outer-loop, and these geophysical values, forward processing, and QC are consistent in GSI. It is very unlikely that surface types are updated before these first outer-loop results are written out in GSI.    However, it is puzzling that there is ice in Georgia.  Maybe, we should also check surface types near this spot.

**Comment by gmao-wgu** [comment] 2022-06-14 13:57
@gmao-jjin3 could you take a look at the surface type at this location from bkg files? that is what the GSI analysis is based on.

**Comment by gmao-jjin3** [comment] 2022-06-14 16:15
Wei, that could give a clue. However, I suspect that CRTM sees different surface types in GSI and UFO. You might be right on this. However, we checked these surface types yesterday and they are the same. Maybe, the surface type in the GEOS output is not the one used in GSI at this spot.  However, this change is not added in UFO.

**Comment by gmao-wgu** [comment] 2022-06-14 16:19
@gmao-jjin3 If that is the case, we can pass this issue and leave it as is.

**Comment by gmao-jjin3** [comment] 2022-06-14 16:45
Wei,  take a look at lines between 1552 ~ 1555 in
/gpfsm/dnb31/jjin3/GEOSadas_git/GEOSadas/src/Components/@GEOSana_GridComp/GEOSaana_GridComp/GSI_GridComp/crtm_interface.f90
It is possible that surface coverage is changed from "land" to "ice" here. However, error inflation is done with land_type=true in GSI.  ice_type = true in UFO since UFO reads ice_coverage and land_coverage in GSI outputs in which these values are already changed in this program.  **As a result, error inflation is done as above ice surface in UFO.**

**Comment by gmao-wgu** [comment] 2022-06-14 16:53
@gmao-jjin3 that is great, then the problem solved and we just leave it as is.

**Comment by gmao-wgu** [comment] 2022-06-14 17:00
I posted the relevant code for reference.  Thank you @gmao-jjin3 
``` fortran
           surface(1)%Lai  = zero
           if (surface(1)%land_coverage>zero) then
              if(lai_type>0)then
                call get_lai(data_s,nchanl,nreal,itime,ilate,lai_type,lai)
                surface(1)%Lai  = lai   ! LAI
              endif

              ! for Glacial land ice soil type and vegetation type
              if(surface(1)%Soil_Type == 9 .OR. surface(1)%Vegetation_Type == 13) then
                 surface(1)%ice_coverage = min(surface(1)%ice_coverage + surface(1)%land_coverage, one)
                 surface(1)%land_coverage = zero
              endif
           endif
```

**Comment by gmao-jjin3** [comment] 2022-06-14 17:11
Thanks. I may have to edit setuprad.f90 and re-run x0044.

**Comment by gmao-jjin3** [comment] 2022-06-15 04:05
Wei, can you give a try of new testing data? They are in the directory: /gpfsm/dnb31/jjin3/jedi/For_others/x0044.jj_20220614/ 

find /gpfsm/dnb31/jjin3/jedi/For_others/x0044.jj_20220614/ -iname "\*iasi_metop-a\*"

**Comment by gmao-wgu** [comment] 2022-06-15 12:51
@gmao-jjin3  Thanks. I will give it a try.

**Comment by gmao-wgu** [comment] 2022-06-16 19:23
@gmao-yzhu  A new QC filter(SurfTypeCheckRad) was developed to reject radiance observations over certain surface types like how we treat ozone channels in IASI in the GSI. This filter can be used as in the following: 
``` fortran
#  Surface Type Check
  - filter: Bounds Check
    filter variables:
    - name: brightness_temperature
      channels: *all_channels
    test variables:
    - name: SurfTypeCheckRad@ObsFunction
      channels: *all_channels
      options:
        channels: *all_channels
        use_flag: *useflag
        use_flag_clddet: *clddet
    maxvalue: 1.0e-12
    defer to post: true
    action:
      name: reject
```
If we want to reject observations over non-water surface types from ozone channels in IASI, simply set clddet value to be 31 for these channels.  The impacts can be seen by comparing the following two plots:

**Without this filter**:
     
![iasi_metop-a Swell_Obs_Number O-F_BC_QC ch266 ps (1)](https://user-images.githubusercontent.com/59488002/174147947-904a0efe-4f6c-4dfd-b5ac-53700461d1fb.png)

**With this filter**:

![iasi_metop-a Swell_Obs_Number O-F_BC_QC ch266 ps (2)](https://user-images.githubusercontent.com/59488002/174148047-1998ec85-71a2-4660-a473-4061e0b74a36.png)

**Comment by gmao-jjin3** [comment] 2022-06-22 14:34
@gmao-wgu,  New data are in /discover/nobackup/jjin3/jedi/For_others/x0044.jj_20220619/

**Comment by gmao-wgu** [comment] 2022-06-22 19:44
@gmao-jjin3 The test files you generated on 20220619 could not produce matched Tb between Jedi and the GSI, but surface types match well.

**Comment by gmao-jjin3** [comment] 2022-06-22 20:37
@gmao-wgu  Is this about iasi_metop-a which has matched data with the old files?

**Comment by gmao-wgu** [comment] 2022-06-22 20:39
@gmao-jjin3 I did not test with iasi-metop-a.

**Comment by gmao-jjin3** [comment] 2022-06-22 21:03
@gmao-wgu Can you test those new iasi_metop-a files? Thanks.

**Comment by gmao-wgu** [comment] 2022-06-22 21:08
@gmao-jjin3 I guess tb will be mismatched too for metop-a

**Comment by gmao-wgu** [comment] 2022-06-22 21:46
@gmao-jjin3 I will use the old one to test metop-b.  Thank you always.

**Comment by gmao-wgu** [comment] 2022-06-29 17:50
For **iasi_metop-b**,  total 18 channels out of 141 do not have the agreement between the GSI and Jedi in terms of the number of observations that can pass their respective QC.  Channel 129 has the difference of 3 and  seven channels: 135 138, 140, 142, 145, 149, 161 have the difference of 2 and the remaining ten channels have the difference of 1.

The histogram plots for channel 107, 129 and 140 are shown in the following:

![iasi_metop-b Swell_Obs_Number O-F_BC_QC ch107 ps](https://user-images.githubusercontent.com/59488002/176504255-f2d338e9-1474-4474-a241-45b14326804f.png)

![iasi_metop-b Swell_Obs_Number O-F_BC_QC ch129 ps](https://user-images.githubusercontent.com/59488002/176502415-08e574f6-d6b4-4431-b4b2-5ce5cdd4bd8b.png)

![iasi_metop-b Swell_Obs_Number O-F_BC_QC ch140 ps](https://user-images.githubusercontent.com/59488002/176502484-24ac8c71-074c-4370-b540-4bd7ee812797.png)

The effective QC flags for these three channels are

![iasi_metop-b Swell_EffectiveQC GsiEffectiveQC ch107 ps](https://user-images.githubusercontent.com/59488002/176504330-a6878b71-f5bf-4eb8-96f4-839aac6dc09e.png)

![iasi_metop-b Swell_EffectiveQC GsiEffectiveQC ch129 ps](https://user-images.githubusercontent.com/59488002/176503309-50fde304-108e-4f41-b7c3-cdb01209cc3b.png)

![iasi_metop-b Swell_EffectiveQC GsiEffectiveQC ch140 ps](https://user-images.githubusercontent.com/59488002/176503365-56d3a19d-2404-4f3c-b44a-e49cf06439fe.png)

The spatial distribution of effective QC flags differences between the GSI and Jedi  for these three channels are 

![GSIQC-JediQC_0_ch107_global](https://user-images.githubusercontent.com/59488002/176508533-9e7d01a7-a821-451b-b2b3-5089e66357a8.png)

So for channel 107, only one observation near the South Pole  that rejected by the GSI cloud detection(Flag =7) still passed QC in Jedi.

![GSIQC_0-JediQC_ch323_global](https://user-images.githubusercontent.com/59488002/176514919-34984beb-9c41-4445-a14b-e082e79cf62e.png)

So for channel 129, there are three observations rejected by bounds check(flag number 12) in the Jedi passed QC in the GSI.

![GSIQC_0-JediQC_ch360_global](https://user-images.githubusercontent.com/59488002/176517708-126e295f-bdf3-4b33-bdf1-43d1e50a9c29.png)
So for channel 140, there are two observations that were rejected by the bounds check in the Jedi passed QC in the GSI.

**It seemed that all differences between the GSI and Jedi occurred over non-water surface types**

**Comment by danholdaway** [comment] 2022-06-29 18:12
Do flags have the same meaning in GSI and JEDI?

**Comment by gmao-wgu** [comment] 2022-06-29 18:30
> Do flags have the same meaning in GSI and JEDI?

Unfortunately, they do not. But in the GSI, each flag has the clear meaning but does not have that in the Jedi. For example, in the GSI, the observations with the flag number 7 means it was rejected by the cloud detection.  While in the Jedi, the observation with the flag number 12 means it was rejected by the bounds check, but we do not know which one: observations range sanity check or cloud detection or NSST retrieval check or gross check

**Comment by gmao-jjin3** [comment] 2022-06-29 19:37
I guess these mismatches are because the lack of manipulation of surface_area_fractions/types in UFO. The manipulation is done in crtm_interface.f90 in GSI. Some of it such as ice_temperature for AMSUA was added in CRTM source code @gmao-yzhu . As to IASI, you can have matched HofX but inflated error with altered surface type. However, you cannot get HofX reproduced with the original (background) surface_area_fraction in the files I recently created.

**Closed as completed** 2023-09-22 16:40 UTC
Labels: ufo done
