### ISSUE TITLE
SE: Flexible swell slurm settings

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#325] opened 2024-04-23 13:34 UTC
With the perspective that there will be a Software Engineering oversight of Swell, let me start list issues that make up good items for SE to work on. 

One such thing is the slurm connection (definition of partition and special queue). The way it is not, Swell wires a single option. The fact is that most users have multiple projects, under different accounts, different qos, different partitions, etc. A more flexible - experiment related (with perhaps a default set, say, as things are presently) will be necessary in not too long.

**Comment by ashiklom** [comment] 2024-04-23 14:02
Tagging myself here. I will take a look at this.

**Comment by rtodling** [comment] 2024-04-23 14:25
Thanks ... you might want to tag yourself to #308 also ... BTW: I have edited existing issue and placed an "SE:" identifier in front of them so we can more clearly know what's seen as system engineering issues. There might be at least one more, at this time ...

**Comment by ashiklom** [comment] 2024-04-23 18:43
Jotting down some notes here while they're fresh on my mind:

- SWELL SLURM configuration happens here. Looks like there's a `~/.swell/swell-slurm` file that can be used for user-specific SLURM configuration. There are also some hard-coded values in here that can be modified. https://github.com/GEOS-ESM/swell/blob/cebcb49b4008485bff0456ec346692bc9cea6367/src/swell/deployment/create_experiment.py#L437-L507
- Cycl allows SLURM directives to be passed via its config files ([link](https://cylc.github.io/cylc-doc/stable/html/user-guide/task-implementation/job-runner-handlers/cylc.flow.job_runner_handlers.slurm.html#module-cylc.flow.job_runner_handlers.slurm)). We can teach SWELL to pass directives from YAML into the cylc `[[directives]]` block.

**Comment by Dooruk** [comment] 2024-04-23 20:24
Could we move this discussion to #308 please. I don't see any difference so we can keep them in the same place? 🙂

**Comment by ashiklom** [comment] 2024-05-03 18:01
Closing issue as duplicate of #308.

**Closed as not planned by ashiklom** 2024-05-03 18:01 UTC
